apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/teocrispy91/argo-test.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: tapp-test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
