apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  selector:
    app: webapp # This selector tells the service to target pods with the label app: webapp
  ports:
    - protocol: TCP
      port: 80 # The port that the service itself will listen on
      targetPort: 80 # The port on the container that the service will forward traffic to
  type: LoadBalancer # Or ClusterIP, NodePort, ExternalNam
